---
# tasks file for tomcat_tomcat

  - name: download tomcat
    get_url: url="{{ tomcat_url }}" dest="/opt"

  - name: extract tomcat
    unarchive: src="/opt/apache-tomcat-{{ tomcat_version }}.tar.gz" dest="/opt" remote_src=yes

  - name: change tomcat port
    template: src=templates/server.xml.j2 dest=/opt/apache-tomcat-{{ tomcat_version }}/conf/server.xml
    notify:
      - stop tomcat
      - start tomcat

  - name: starting tomcat
    command: "nohup /opt/apache-tomcat-{{ tomcat_version }}/bin/startup.sh"

