---
- name: install and configure tomcat on webserver group
  hosts: webserver
  gather_facts: false
  become: true
  vars:
    java_version: java-1.8.0-openjdk
    tomcat_port: 6060
    tomcat_version: "9.0.37"
    tomcat_url: "https://mirrors.estointernet.in/apache/tomcat/tomcat-{{ tomcat_version.split('.')[0] }}/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"
  tasks:
    - name: install java
      yum: name={{ java_version}} state=present update_cache=yes

    - name: download tomcat
      get_url: url="{{ tomcat_url }}" dest="/opt"

    - name: extract tomcat
      unarchive: src="/opt/apache-tomcat-{{ tomcat_version }}.tar.gz" dest="/opt" remote_src=yes

    - name: change tomcat port
      template: src=template/server.xml.j2 dest=/opt/apache-tomcat-{{ tomcat_version }}/conf/server.xml
      notify:
        - stop tomcat
        - start tomcat

    - name: starting tomcat
      command: "nohup /opt/apache-tomcat-{{ tomcat_version }}/bin/startup.sh"

  handlers:
    - name: stop tomcat
      command: /opt/apache-tomcat-{{ tomcat_version }}/bin/shutdown.sh
      ignore_errors: yes

    - name: start tomcat
      command: nohup /opt/apache-tomcat-{{ tomcat_version }}/bin/startup.sh
