---
  - hosts: database
    become: true
    tasks:
      - name: install mysql-server
        yum:
          name: mysql
          state: present
          update_cache: yes
      - name: check mysql service
        service:
          name: mysql
          state: started
          enabled: yes
