---
- hosts: control
  gather_facts: no
  tasks:
    - name: check /home contents
      command: ls -l /home
      register: home_output

    - name: fail above task if rc==0
      fail: msg="Failed because return code is 0"
      when: home_output.rc==0
