---
- hosts: control
  become: yes
  tasks:
    - name: install apache2
      apt: name=apache2 state=present update_cache=yes
      when: ansible_distribution=="Ubuntu"
      notify: restart apache2

    - name: install httpd
      yum: name=httpd state=present update_cache=yes
      when: ansible_distribution!="Ubuntu"
      notify: 
        - restart httpd

  handlers:
    - name: start apache2
      service: name=apache2 state=started

    - name: start httpd
      service: name=httpd state=started
