---
- hosts: control
  become: true
  tasks:
    - name: install apache2
      apt: name=apache2 state=present update_cache=yes
      register: out

    - name: start apache2 if it gets installed from above task
      service: name=apache2 state=started
      when: out.changed==true
