---
- hosts: control
  gather_facts: no
  vars:
    x: 4
    quote: "life is what we make it!"
    my_path: "/home/ansible/tmp"
  tasks:
    - name: test operators 
      debug:
        msg:
          - "x : {{ x }}"
          - "quote is '{{ quote }}'" 
          - "variable x is defined : {{ x is defined }}"
          - "variable y is defined : {{ y is defined }}"
          - "variable z is not defined : {{ z is not defined }}"
          - "variable a is undefined : {{ a is undefined }}"
          - "string quote is lower : {{ quote is lower }}"
          - "string quote is upper : {{ quote is upper }}"
          - "quote is string : {{ quote is string }}"
          - "quote is not string : {{ quote is not string }}"
          - "x is number : {{ x is number }}"
          - "x is not number : {{ x is not number }}"
          - "x is divisible by 2 : {{ x is divisibleby 2 }}"
          - "x is not divisible by 2 : {{ x is not divisibleby 2 }}"
          - "x is even : {{ x is even }}"
          - "x is odd : {{ x is odd }}"
          - "my_path is : {{ my_path }}"
          - "my_path is a file : {{ my_path is file }}"
          - "my_path is a directory : {{ my_path is directory }}"
          - "my_path exists : {{ my_path is exists }}"
          - "my_path is a link : {{ my_path is link }}"
