---
  - hosts: control
    become: true
    tasks:
      - name: change hostname of ansible controller permanently
        lineinfile: dest=/etc/hostname regexp=ip-172-31-45-130 line="ansible-controller"
        notify: reboot server

      - name: update /etc/hosts file on ansible-controller
        blockinfile:
          path: /etc/hosts
          backup: yes
          block: |
            172.31.45.130       ansible-controller
            172.31.35.243       lb01
            172.31.47.68        app01
            172.31.37.198       app02
            172.31.32.28        db01

      - name: update /etc/ssh/sshd_config to increase session timeout
        lineinfile: dest=/etc/ssh/sshd_config regexp=^#ClientAliveInterval line="ClientAliveInterval 5m"
        notify: restart sshd

      - name: update /etc/ssh/sshd_config to increase session timeout
        lineinfile: dest=/etc/ssh/sshd_config regexp=^#ClientAliveCountMax line="ClientAliveCountMax 4"
        notify: restart sshd
      
      - name: install tools
        apt: name={{item}} state=present update_cache=yes
        with_items:
          - curl
          - whois
          - python-httplib2
          - zip

    handlers:
      - name: reboot server
        reboot:

      - name: restart sshd
        service: name=sshd state=restarted

