---
  - hosts: webserver
    become: true
    tasks:
      - name: install apache2
        apt: name=apache2 state=present update_cache=yes

      - name: install libapache2-mod-wsgi
        apt: name=libapache2-mod-wsgi state=present update_cache=yes

      - name: install python-pip
        apt: name=python-pip state=present update_cache=yes

      - name: install python-virtualenv
        apt: name=python-virtualenv state=present update_cache=yes
