---
  # Bring stack down
  - hosts: loadbalancer
    become: true
    tasks:
      - name: stop nginx
        service: name=nginx state=stopped

      - wait_for: port=80 state=drained         # drained state will ensure all current active sessions are completely closed and no new sessions

  - hosts: webserver
    become: true
    tasks:
      - name: stop apache2
        service: name=apache2 state=stopped
       
      - wait_for: port=80 state=stopped

  # restart mysql
  - hosts: database
    become: true
    tasks:
      - name: restart mysql
        service: name=mysql state=restarted
      
      - wait_for: port=3306 state=started

  # Bring stack up
  - hosts: webserver
    become: true
    tasks:
      - name: start apache2
        service: name=apache2 state=started
      
      - wait_for: port=80                       # even if we don't mention state=started, the default state is started for this module

  - hosts: loadbalancer
    become: true
    tasks:
      - name: start nginx
        service: name=nginx state=started
       
      - wait_for: port=80 
